name: Build Tauri AppImage
description: Build Tauri v2 application as Linux AppImage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            squashfs-tools \
            libfuse2 \
            file \
            python3-pip
          pip install appimage-builder

      - name: Install JS deps
        shell: bash
        run: yarn install --frozen-lockfile

      - name: Build AppImage
        shell: bash
        run: yarn tauri build

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-appimage
          path: src-tauri/target/release/bundle/appimage/*.AppImage
